### ISSUE TITLE
Background and Purpose--inclusion of ERP products

### ISSUE THREAD

**Issue by jgb1128** [commoncriteria/enterprise-management#1]
"This software encompasses tools for areas like finance, accounting, supply chain, HR, customer relationships, project management,
and even infrastructure monitoring." This seems to be including Enterprise Resource Planning technologies.  Examples include:

- PeopleSoft
- SAP
- Oracle Financials
- Workday

ERPs are a class of large products used to manage back offices of businesses.  The security functionality of ERPs is dependent on the underlying O/S, DB's, App Servers etc that do provide security functions.  
Installation, configuration and deployment of ERPs are very complicated and typically require 3rd party assistance (not COTs).  
As far as I know, ERPs have never been subject to Common Criteria.  CC is traditionally for security enforcing and supporting products it would be good to know if customers are demanding CC evaluations of ERPs before making this a requirement.

**Comment by dkehs** [comment]
Hey Josh, just dropping back in on this. We do agree that this is likely too broad of a statement for this Protection Profile and will look for feedback on an updated "higher-level" definition focusing instead on EM systems being used to deploy software and manage systems.

**Comment by jgb1128** [comment]
> Hey Josh, just dropping back in on this. We do agree that this is likely too broad of a statement for this Protection Profile and will look for feedback on an updated "higher-level" definition focusing instead on EM systems being used to deploy software and manage systems.

Thank you. I look forward to your updated write up.

**Comment by dkehs** [comment]
We have updated this specific paragraph as follows:
"Enterprise Management (EM) systems are used to deploy software and manage systems in an enterprise. EM systems typically consist of a host, and may include endpoint host agents to allow for the discovery, reporting and remediation of IT policy and security issues."
